# .github/workflows/terraform.yml
name: Terraform

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:  # This line allows manual triggering of the workflow


jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Optional, set the timeout limit for the job
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }} 
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-key.json 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Authenticate with GCP
        if: env.GOOGLE_CREDENTIALS != ''
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > $GITHUB_WORKSPACE/gcloud-key.json

      - name: Terraform Init
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS
          terraform init
        working-directory: ./terraform

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./terraform
